/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-10 17:29:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.MPaymentDao;
import model.Maintenance;
import model.Member;
import model.Admin;
import dao.AdminDao;
import java.util.List;

public final class admin_002dview_002dmpayment_002dby_002dmid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin-header.jsp", Long.valueOf(1683739697915L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dao.MPaymentDao");
    _jspx_imports_classes.add("model.Admin");
    _jspx_imports_classes.add("dao.AdminDao");
    _jspx_imports_classes.add("model.Maintenance");
    _jspx_imports_classes.add("model.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Admin Panel</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<meta name=\"keywords\" content=\"Glance Design Dashboard Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \n");
      out.write("SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\n");
      out.write("\n");
      out.write("<!-- Bootstrap Core CSS -->\n");
      out.write("<link href=\"admin/assets/css/bootstrap.css\" rel='stylesheet' type='text/css' />\n");
      out.write("\n");
      out.write("<!-- Custom CSS -->\n");
      out.write("<link href=\"admin/assets/css/style.css\" rel='stylesheet' type='text/css' />\n");
      out.write("\n");
      out.write("<!-- font-awesome icons CSS -->\n");
      out.write("<link href=\"admin/assets/css/font-awesome.css\" rel=\"stylesheet\"> \n");
      out.write("<!-- //font-awesome icons CSS-->\n");
      out.write("\n");
      out.write("<!-- side nav css file -->\n");
      out.write("<link href='admin/assets/css/SidebarNav.min.css' media='all' rel='stylesheet' type='text/css'/>\n");
      out.write("<!-- //side nav css file -->\n");
      out.write(" \n");
      out.write(" <!-- js-->\n");
      out.write("<script src=\"admin/assets/js/jquery-1.11.1.min.js\"></script>\n");
      out.write("<script src=\"admin/assets/js/modernizr.custom.js\"></script>\n");
      out.write("\n");
      out.write("<!--webfonts-->\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext\" rel=\"stylesheet\">\n");
      out.write("<!--//webfonts--> \n");
      out.write("\n");
      out.write("<!-- chart -->\n");
      out.write("<script src=\"admin/assets/js/Chart.js\"></script>\n");
      out.write("<!-- //chart -->\n");
      out.write("\n");
      out.write("<!-- Metis Menu -->\n");
      out.write("<script src=\"admin/assets/js/metisMenu.min.js\"></script>\n");
      out.write("<script src=\"admin/assets/js/custom.js\"></script>\n");
      out.write("<link href=\"admin/assets/css/custom.css\" rel=\"stylesheet\">\n");
      out.write("<!--//Metis Menu -->\n");
      out.write("<style>\n");
      out.write("#chartdiv {\n");
      out.write("  width: 100%;\n");
      out.write("  height: 295px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<!--pie-chart --><!-- index page sales reviews visitors pie chart -->\n");
      out.write("<script src=\"admin/assets/js/pie-chart.js\" type=\"text/javascript\"></script>\n");
      out.write(" <script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("        $(document).ready(function () {\n");
      out.write("            $('#demo-pie-1').pieChart({\n");
      out.write("                barColor: '#2dde98',\n");
      out.write("                trackColor: '#eee',\n");
      out.write("                lineCap: 'round',\n");
      out.write("                lineWidth: 8,\n");
      out.write("                onStep: function (from, to, percent) {\n");
      out.write("                    $(this.element).find('.pie-value').text(Math.round(percent) + '%');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $('#demo-pie-2').pieChart({\n");
      out.write("                barColor: '#8e43e7',\n");
      out.write("                trackColor: '#eee',\n");
      out.write("                lineCap: 'butt',\n");
      out.write("                lineWidth: 8,\n");
      out.write("                onStep: function (from, to, percent) {\n");
      out.write("                    $(this.element).find('.pie-value').text(Math.round(percent) + '%');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $('#demo-pie-3').pieChart({\n");
      out.write("                barColor: '#ffc168',\n");
      out.write("                trackColor: '#eee',\n");
      out.write("                lineCap: 'square',\n");
      out.write("                lineWidth: 8,\n");
      out.write("                onStep: function (from, to, percent) {\n");
      out.write("                    $(this.element).find('.pie-value').text(Math.round(percent) + '%');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("           \n");
      out.write("        });\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("<!-- //pie-chart --><!-- index page sales reviews visitors pie chart -->\n");
      out.write("\n");
      out.write("	<!-- requried-jsfiles-for owl -->\n");
      out.write("					<link href=\"admin/assets/css/owl.carousel.css\" rel=\"stylesheet\">\n");
      out.write("					<script src=\"admin/assets/js/owl.carousel.js\"></script>\n");
      out.write("						<script>\n");
      out.write("							$(document).ready(function() {\n");
      out.write("								$(\"#owl-demo\").owlCarousel({\n");
      out.write("									items : 3,\n");
      out.write("									lazyLoad : true,\n");
      out.write("									autoPlay : true,\n");
      out.write("									pagination : true,\n");
      out.write("									nav:true,\n");
      out.write("								});\n");
      out.write("							});\n");
      out.write("						</script>\n");
      out.write("					<!-- //requried-jsfiles-for owl -->\n");
      out.write("</head> \n");
      out.write("<body class=\"cbp-spmenu-push\">\n");
      out.write("\n");

	Admin a = null;
	if(session.getAttribute("adminData")!=null)
	{
		a = (Admin)session.getAttribute("adminData");
		System.out.println(a.getName());
	}
	else
	{
		response.sendRedirect("admin-login.jsp");
	}

      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"main-content\">\n");
      out.write("	<div class=\"cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left\" id=\"cbp-spmenu-s1\">\n");
      out.write("		<!--left-fixed -navigation-->\n");
      out.write("		<aside class=\"sidebar-left\">\n");
      out.write("      <nav class=\"navbar navbar-inverse\">\n");
      out.write("          <div class=\"navbar-header\">\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\".collapse\" aria-expanded=\"false\">\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            </button>\n");
      out.write("            <h1><a class=\"navbar-brand\" href=\"index.html\"><span class=\"fa fa-area-chart\"></span> E-Society<span class=\"dashboard_text\">Manager dashboard</span></a></h1>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("            <ul class=\"sidebar-menu\">\n");
      out.write("              <li class=\"header\">Manage From Here<li>\n");
      out.write("              <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-home.jsp\">\n");
      out.write("                <i class=\"fa fa-dashboard\"></i> <span>Dashboard</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("			  <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-view-all-members.jsp\">\n");
      out.write("                <i class=\"fa fa-users\"></i>\n");
      out.write("                <span>Society Members</span>\n");
      out.write("                \n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-approve-registration-request.jsp\">\n");
      out.write("                <i class=\"fa fa-check-square-o\"></i>\n");
      out.write("                <span>Approve Request</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-manage-complaint.jsp\">\n");
      out.write("                <i class=\"fa fa-pie-chart\"></i>\n");
      out.write("                <span>Manage Complaint</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-view-all-notice.jsp\">\n");
      out.write("                <i class=\"fa fa-file-text-o\"></i>\n");
      out.write("                <span>Manage Society Circular</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("\n");
      out.write("               \n");
      out.write("               <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-view-hall-booking.jsp\">\n");
      out.write("                <i class=\"fa fa-calendar-o\"></i>\n");
      out.write("                <span>Hall Booking</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              \n");
      out.write("              <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-view-all-event.jsp\">\n");
      out.write("                <i class=\"fa fa-calendar-o\"></i>\n");
      out.write("                <span>Society Event</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              \n");
      out.write("              <li class=\"treeview\">\n");
      out.write("              <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-view-hall-payment.jsp\">\n");
      out.write("                <i class=\"fa fa-money\"></i>\n");
      out.write("				<span>All Payments</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("			  <li>\n");
      out.write("                <a href=\"admin-logout.jsp\">\n");
      out.write("                <i class=\"fa fa-th\"></i> <span>Sign Out</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              \n");
      out.write("          </div>\n");
      out.write("          <!-- /.navbar-collapse -->\n");
      out.write("      </nav>\n");
      out.write("    </aside>\n");
      out.write("	</div>\n");
      out.write("		<!--left-fixed -navigation-->\n");
      out.write("		\n");
      out.write("			<div class=\"header-right\">\n");
      out.write("				\n");
      out.write("				\n");
      out.write("				<!--search-box-->\n");
      out.write("				\n");
      out.write("				\n");
      out.write("				<div class=\"profile_details\">		\n");
      out.write("					<ul>\n");
      out.write("						<li class=\"dropdown profile_details_drop\">\n");
      out.write("							<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("								<div class=\"profile_img\">	\n");
      out.write("									<span class=\"prfil-img\"><img src=\"images/2.jpg\" alt=\"\"> </span> \n");
      out.write("									<div class=\"user-name\">\n");
      out.write("									<p>");
      out.print(a.getName() );
      out.write("</p>\n");
      out.write("									<span>");
      out.print(a.getEmail() );
      out.write("</span>\n");
      out.write("									</div>\n");
      out.write("									<i class=\"fa fa-angle-down lnr\"></i>\n");
      out.write("									<i class=\"fa fa-angle-up lnr\"></i>\n");
      out.write("									<div class=\"clearfix\"></div>	\n");
      out.write("								</div>	\n");
      out.write("							</a>\n");
      out.write("							<ul class=\"dropdown-menu drp-mnu\">\n");
      out.write("								<li> <a href=\"#\"><i class=\"fa fa-cog\"></i> Settings</a> </li> \n");
      out.write("								<li> <a href=\"#\"><i class=\"fa fa-user\"></i> My Account</a> </li> \n");
      out.write("								<li> <a href=\"#\"><i class=\"fa fa-suitcase\"></i> Profile</a> </li> \n");
      out.write("								<li> <a href=\"#\"><i class=\"fa fa-sign-out\"></i> Logout</a> </li>\n");
      out.write("							</ul>\n");
      out.write("						</li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"clearfix\"> </div>				\n");
      out.write("			</div>\n");
      out.write("			<div class=\"clearfix\"> </div>	\n");
      out.write("		</div>\n");
      out.write("		<!-- //header-ends -->\n");
      out.write("	</div>");
      out.write("\r\n");
      out.write("<!-- main content start-->\r\n");
      out.write("\r\n");
      out.write("<div id=\"page-wrapper\">\r\n");
      out.write("	<div class=\"main-page\">\r\n");
      out.write("		<div class=\"tables\">\r\n");
      out.write("			<h2 class=\"title1\">View All Members Payment</h2>\r\n");
      out.write("			\r\n");
      out.write("			<form action=\"HallBookController\" method=\"post\">\r\n");
      out.write("			\r\n");
      out.write("			<button type = \"submit\" class = \"btn btn-danger\" name=\"action\" value=\"adminViewAllHAllPayment\">All Hall Rent Payments</button>\r\n");
      out.write("			\r\n");
      out.write("			<button type = \"submit\" class = \"btn btn-primary\" name=\"action\" value=\"adminViewAllMaintenancePayment\">All Maintenance Payments</button>\r\n");
      out.write("		\r\n");
      out.write("			\r\n");
      out.write("			</form>	\r\n");
      out.write("\r\n");
      out.write("				<div class=\"forms\">\r\n");
      out.write("					<div class=\"inline-form widget-shadow\">\r\n");
      out.write("						<div class=\"form-body\">\r\n");
      out.write("							<div data-example-id=\"simple-form-inline\"> \r\n");
      out.write("							<form action=\"HallBookController\" method=\"post\" class=\"form-inline\"> \r\n");
      out.write("								<div class=\"form-group\"> \r\n");
      out.write("									<input type=\"text\" class=\"form-control\" id=\"exampleInputEmail3\" name=\"mid\"  placeholder=\"Enter Member ID\"> \r\n");
      out.write("								</div> \r\n");
      out.write("								<button type=\"submit\" class=\"btn btn-default\" name=\"action\" value=\"AdminViewMPaymentByMid\">View Maintenance Payment</button> \r\n");
      out.write("							</form> \r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("<div class=\"bs-example widget-shadow\" data-example-id=\"contextual-table\"> \r\n");
      out.write("					<h4>Maintenance Payments:</h4>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<table class=\"table\"> \r\n");
      out.write("					<thead> \r\n");
      out.write("					<tr> \r\n");
      out.write("					<th>Payment ID</th> \r\n");
      out.write("					<th>Member ID</th> \r\n");
      out.write("					<th>Member Name</th>\r\n");
      out.write("					<th>House No</th>\r\n");
      out.write("					<th>Date Of Joining</th>\r\n");
      out.write("					<th>Date of Payment</th>\r\n");
      out.write("					<th>Amount</th>\r\n");
      out.write("					\r\n");
      out.write("					    \r\n");
      out.write("					</tr> \r\n");
      out.write("					</thead> \r\n");
      out.write("					<tbody> \r\n");
      out.write("					");
 int mid = Integer.parseInt(request.getParameter("mid")); 
      out.write("\r\n");
      out.write("					");
List<Maintenance> list1 = MPaymentDao.getMaintenanceByMid(mid); 
      out.write("\r\n");
      out.write("					");
for(Maintenance m1 : list1){ 
      out.write("\r\n");
      out.write("					<tr class=\"active\"> \r\n");
      out.write("					<th scope=\"row\">");
      out.print(m1.getMp_id() );
      out.write("</th> \r\n");
      out.write("					<td>");
      out.print(m1.getMid() );
      out.write("</td> \r\n");
      out.write("						");
List<Member> list2 = AdminDao.getMemberByMid(m1.getMid());
      out.write("\r\n");
      out.write("						");
for(Member m2 : list2){ 
      out.write("\r\n");
      out.write("						<td>");
      out.print(m2.getFname() );
      out.write(' ');
      out.print(m2.getLname() );
      out.write("</td> \r\n");
      out.write("						<td>");
      out.print(m2.getH_no() );
      out.write("</td>\r\n");
      out.write("						<td>");
      out.print(m2.getJoin_date() );
      out.write("</td> \r\n");
      out.write("						");
} 
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					<td>");
      out.print(m1.getM_date() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(m1.getM_amount()  );
      out.write("</td>\r\n");
      out.write("					\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("					\r\n");
      out.write("					</tr> \r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("					</tbody> \r\n");
      out.write("					</table> \r\n");
      out.write("				</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	<!-- side nav js -->\r\n");
      out.write("	<script src='admin/assets/js/SidebarNav.min.js' type='text/javascript'></script>\r\n");
      out.write("	<script>\r\n");
      out.write("      $('.sidebar-menu').SidebarNav()\r\n");
      out.write("    </script>\r\n");
      out.write("	<!-- //side nav js -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- Classie --><!-- for toggle left push menu script -->\r\n");
      out.write("		<script src=\"admin/assets/js/classie.js\"></script>\r\n");
      out.write("		<script>\r\n");
      out.write("			var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),\r\n");
      out.write("				showLeftPush = document.getElementById( 'showLeftPush' ),\r\n");
      out.write("				body = document.body;\r\n");
      out.write("				\r\n");
      out.write("			showLeftPush.onclick = function() {\r\n");
      out.write("				classie.toggle( this, 'active' );\r\n");
      out.write("				classie.toggle( body, 'cbp-spmenu-push-toright' );\r\n");
      out.write("				classie.toggle( menuLeft, 'cbp-spmenu-open' );\r\n");
      out.write("				disableOther( 'showLeftPush' );\r\n");
      out.write("			};\r\n");
      out.write("			\r\n");
      out.write("			function disableOther( button ) {\r\n");
      out.write("				if( button !== 'showLeftPush' ) {\r\n");
      out.write("					classie.toggle( showLeftPush, 'disabled' );\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("	<!-- //Classie --><!-- //for toggle left push menu script -->\r\n");
      out.write("	\r\n");
      out.write("	<!--scrolling js-->\r\n");
      out.write("	<script src=\"admin/assets/js/jquery.nicescroll.js\"></script>\r\n");
      out.write("	<script src=\"admin/assets/js/scripts.js\"></script>\r\n");
      out.write("	<!--//scrolling js-->\r\n");
      out.write("	\r\n");
      out.write("	<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("	<script src=\"admin/assets/js/bootstrap.js\"> </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
