/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-30 09:14:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.AdminDao;
import model.HallBook;
import dao.MemberDao;
import model.Member;
import java.util.List;
import model.Admin;
import dao.AdminDao;
import java.util.List;

public final class admin_002dhall_002dbooking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin-header.jsp", Long.valueOf(1682691439646L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.MemberDao");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.HallBook");
    _jspx_imports_classes.add("model.Admin");
    _jspx_imports_classes.add("dao.AdminDao");
    _jspx_imports_classes.add("model.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("  \n");
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Admin Book Hall</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Admin Panel</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<meta name=\"keywords\" content=\"Glance Design Dashboard Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \n");
      out.write("SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\n");
      out.write("\n");
      out.write("<!-- Bootstrap Core CSS -->\n");
      out.write("<link href=\"admin/assets/css/bootstrap.css\" rel='stylesheet' type='text/css' />\n");
      out.write("\n");
      out.write("<!-- Custom CSS -->\n");
      out.write("<link href=\"admin/assets/css/style.css\" rel='stylesheet' type='text/css' />\n");
      out.write("\n");
      out.write("<!-- font-awesome icons CSS -->\n");
      out.write("<link href=\"admin/assets/css/font-awesome.css\" rel=\"stylesheet\"> \n");
      out.write("<!-- //font-awesome icons CSS-->\n");
      out.write("\n");
      out.write("<!-- side nav css file -->\n");
      out.write("<link href='admin/assets/css/SidebarNav.min.css' media='all' rel='stylesheet' type='text/css'/>\n");
      out.write("<!-- //side nav css file -->\n");
      out.write(" \n");
      out.write(" <!-- js-->\n");
      out.write("<script src=\"admin/assets/js/jquery-1.11.1.min.js\"></script>\n");
      out.write("<script src=\"admin/assets/js/modernizr.custom.js\"></script>\n");
      out.write("\n");
      out.write("<!--webfonts-->\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext\" rel=\"stylesheet\">\n");
      out.write("<!--//webfonts--> \n");
      out.write("\n");
      out.write("<!-- chart -->\n");
      out.write("<script src=\"admin/assets/js/Chart.js\"></script>\n");
      out.write("<!-- //chart -->\n");
      out.write("\n");
      out.write("<!-- Metis Menu -->\n");
      out.write("<script src=\"admin/assets/js/metisMenu.min.js\"></script>\n");
      out.write("<script src=\"admin/assets/js/custom.js\"></script>\n");
      out.write("<link href=\"admin/assets/css/custom.css\" rel=\"stylesheet\">\n");
      out.write("<!--//Metis Menu -->\n");
      out.write("<style>\n");
      out.write("#chartdiv {\n");
      out.write("  width: 100%;\n");
      out.write("  height: 295px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<!--pie-chart --><!-- index page sales reviews visitors pie chart -->\n");
      out.write("<script src=\"admin/assets/js/pie-chart.js\" type=\"text/javascript\"></script>\n");
      out.write(" <script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("        $(document).ready(function () {\n");
      out.write("            $('#demo-pie-1').pieChart({\n");
      out.write("                barColor: '#2dde98',\n");
      out.write("                trackColor: '#eee',\n");
      out.write("                lineCap: 'round',\n");
      out.write("                lineWidth: 8,\n");
      out.write("                onStep: function (from, to, percent) {\n");
      out.write("                    $(this.element).find('.pie-value').text(Math.round(percent) + '%');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $('#demo-pie-2').pieChart({\n");
      out.write("                barColor: '#8e43e7',\n");
      out.write("                trackColor: '#eee',\n");
      out.write("                lineCap: 'butt',\n");
      out.write("                lineWidth: 8,\n");
      out.write("                onStep: function (from, to, percent) {\n");
      out.write("                    $(this.element).find('.pie-value').text(Math.round(percent) + '%');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $('#demo-pie-3').pieChart({\n");
      out.write("                barColor: '#ffc168',\n");
      out.write("                trackColor: '#eee',\n");
      out.write("                lineCap: 'square',\n");
      out.write("                lineWidth: 8,\n");
      out.write("                onStep: function (from, to, percent) {\n");
      out.write("                    $(this.element).find('.pie-value').text(Math.round(percent) + '%');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("           \n");
      out.write("        });\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("<!-- //pie-chart --><!-- index page sales reviews visitors pie chart -->\n");
      out.write("\n");
      out.write("	<!-- requried-jsfiles-for owl -->\n");
      out.write("					<link href=\"admin/assets/css/owl.carousel.css\" rel=\"stylesheet\">\n");
      out.write("					<script src=\"admin/assets/js/owl.carousel.js\"></script>\n");
      out.write("						<script>\n");
      out.write("							$(document).ready(function() {\n");
      out.write("								$(\"#owl-demo\").owlCarousel({\n");
      out.write("									items : 3,\n");
      out.write("									lazyLoad : true,\n");
      out.write("									autoPlay : true,\n");
      out.write("									pagination : true,\n");
      out.write("									nav:true,\n");
      out.write("								});\n");
      out.write("							});\n");
      out.write("						</script>\n");
      out.write("					<!-- //requried-jsfiles-for owl -->\n");
      out.write("</head> \n");
      out.write("<body class=\"cbp-spmenu-push\">\n");
      out.write("\n");

	Admin a = null;
	if(session.getAttribute("adminData")!=null)
	{
		a = (Admin)session.getAttribute("adminData");
		System.out.println(a.getName());
	}
	else
	{
		response.sendRedirect("admin-login.jsp");
	}

      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"main-content\">\n");
      out.write("	<div class=\"cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left\" id=\"cbp-spmenu-s1\">\n");
      out.write("		<!--left-fixed -navigation-->\n");
      out.write("		<aside class=\"sidebar-left\">\n");
      out.write("      <nav class=\"navbar navbar-inverse\">\n");
      out.write("          <div class=\"navbar-header\">\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\".collapse\" aria-expanded=\"false\">\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            </button>\n");
      out.write("            <h1><a class=\"navbar-brand\" href=\"index.html\"><span class=\"fa fa-area-chart\"></span> E-Society<span class=\"dashboard_text\">Manager dashboard</span></a></h1>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("            <ul class=\"sidebar-menu\">\n");
      out.write("              <li class=\"header\">Manage From Here<li>\n");
      out.write("              <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-home.jsp\">\n");
      out.write("                <i class=\"fa fa-dashboard\"></i> <span>Dashboard</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("			  <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-view-all-members.jsp\">\n");
      out.write("                <i class=\"fa fa-users\"></i>\n");
      out.write("                <span>Society Members</span>\n");
      out.write("                \n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-approve-registration-request.jsp\">\n");
      out.write("                <i class=\"fa fa-check-square-o\"></i>\n");
      out.write("                <span>Approve Request</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-manage-complaint.jsp\">\n");
      out.write("                <i class=\"fa fa-pie-chart\"></i>\n");
      out.write("                <span>Manage Complaint</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-view-all-notice.jsp\">\n");
      out.write("                <i class=\"fa fa-file-text-o\"></i>\n");
      out.write("                <span>Manage Society Circular</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("\n");
      out.write("               \n");
      out.write("               <li class=\"treeview\">\n");
      out.write("                <a href=\"admin-view-hall-booking.jsp\">\n");
      out.write("                <i class=\"fa fa-calendar-o\"></i>\n");
      out.write("                <span>Hall Booking</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"treeview\">\n");
      out.write("              <li class=\"treeview\">\n");
      out.write("                <a href=\"#\">\n");
      out.write("                <i class=\"fa fa-money\"></i>\n");
      out.write("				<span>Payment</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("			  <li>\n");
      out.write("                <a href=\"admin-logout.jsp\">\n");
      out.write("                <i class=\"fa fa-th\"></i> <span>Sign Out</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              \n");
      out.write("          </div>\n");
      out.write("          <!-- /.navbar-collapse -->\n");
      out.write("      </nav>\n");
      out.write("    </aside>\n");
      out.write("	</div>\n");
      out.write("		<!--left-fixed -navigation-->\n");
      out.write("		\n");
      out.write("		<!-- header-starts -->\n");
      out.write("		<div class=\"sticky-header header-section \">\n");
      out.write("			<div class=\"header-left\">\n");
      out.write("				<!--toggle button start-->\n");
      out.write("				<button id=\"showLeftPush\"><i class=\"fa fa-bars\"></i></button>\n");
      out.write("				<!--toggle button end-->\n");
      out.write("				<div class=\"profile_details_left\"><!--notifications of menu start -->\n");
      out.write("					<ul class=\"nofitications-dropdown\">\n");
      out.write("						<li class=\"dropdown head-dpdn\">\n");
      out.write("							<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fa fa-envelope\"></i><span class=\"badge\">4</span></a>\n");
      out.write("							<ul class=\"dropdown-menu\">\n");
      out.write("								<li>\n");
      out.write("									<div class=\"notification_header\">\n");
      out.write("										<h3>You have 3 new messages</h3>\n");
      out.write("									</div>\n");
      out.write("								</li>\n");
      out.write("								<li><a href=\"#\">\n");
      out.write("								   <div class=\"user_img\"><img src=\"images/1.jpg\" alt=\"\"></div>\n");
      out.write("								   <div class=\"notification_desc\">\n");
      out.write("									<p>Lorem ipsum dolor amet</p>\n");
      out.write("									<p><span>1 hour ago</span></p>\n");
      out.write("									</div>\n");
      out.write("								   <div class=\"clearfix\"></div>	\n");
      out.write("								</a></li>\n");
      out.write("								<li class=\"odd\"><a href=\"#\">\n");
      out.write("									<div class=\"user_img\"><img src=\"images/4.jpg\" alt=\"\"></div>\n");
      out.write("								   <div class=\"notification_desc\">\n");
      out.write("									<p>Lorem ipsum dolor amet </p>\n");
      out.write("									<p><span>1 hour ago</span></p>\n");
      out.write("									</div>\n");
      out.write("								  <div class=\"clearfix\"></div>	\n");
      out.write("								</a></li>\n");
      out.write("								<li><a href=\"#\">\n");
      out.write("								   <div class=\"user_img\"><img src=\"images/3.jpg\" alt=\"\"></div>\n");
      out.write("								   <div class=\"notification_desc\">\n");
      out.write("									<p>Lorem ipsum dolor amet </p>\n");
      out.write("									<p><span>1 hour ago</span></p>\n");
      out.write("									</div>\n");
      out.write("								   <div class=\"clearfix\"></div>	\n");
      out.write("								</a></li>\n");
      out.write("								<li><a href=\"#\">\n");
      out.write("								   <div class=\"user_img\"><img src=\"images/2.jpg\" alt=\"\"></div>\n");
      out.write("								   <div class=\"notification_desc\">\n");
      out.write("									<p>Lorem ipsum dolor amet </p>\n");
      out.write("									<p><span>1 hour ago</span></p>\n");
      out.write("									</div>\n");
      out.write("								   <div class=\"clearfix\"></div>	\n");
      out.write("								</a></li>\n");
      out.write("								<li>\n");
      out.write("									<div class=\"notification_bottom\">\n");
      out.write("										<a href=\"#\">See all messages</a>\n");
      out.write("									</div> \n");
      out.write("								</li>\n");
      out.write("							</ul>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"dropdown head-dpdn\">\n");
      out.write("							<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fa fa-bell\"></i><span class=\"badge blue\">4</span></a>\n");
      out.write("							<ul class=\"dropdown-menu\">\n");
      out.write("								<li>\n");
      out.write("									<div class=\"notification_header\">\n");
      out.write("										<h3>You have 3 new notification</h3>\n");
      out.write("									</div>\n");
      out.write("								</li>\n");
      out.write("								<li><a href=\"#\">\n");
      out.write("									<div class=\"user_img\"><img src=\"images/4.jpg\" alt=\"\"></div>\n");
      out.write("								   <div class=\"notification_desc\">\n");
      out.write("									<p>Lorem ipsum dolor amet</p>\n");
      out.write("									<p><span>1 hour ago</span></p>\n");
      out.write("									</div>\n");
      out.write("								  <div class=\"clearfix\"></div>	\n");
      out.write("								 </a></li>\n");
      out.write("								 <li class=\"odd\"><a href=\"#\">\n");
      out.write("									<div class=\"user_img\"><img src=\"images/1.jpg\" alt=\"\"></div>\n");
      out.write("								   <div class=\"notification_desc\">\n");
      out.write("									<p>Lorem ipsum dolor amet </p>\n");
      out.write("									<p><span>1 hour ago</span></p>\n");
      out.write("									</div>\n");
      out.write("								   <div class=\"clearfix\"></div>	\n");
      out.write("								 </a></li>\n");
      out.write("								 <li><a href=\"#\">\n");
      out.write("									<div class=\"user_img\"><img src=\"images/3.jpg\" alt=\"\"></div>\n");
      out.write("								   <div class=\"notification_desc\">\n");
      out.write("									<p>Lorem ipsum dolor amet </p>\n");
      out.write("									<p><span>1 hour ago</span></p>\n");
      out.write("									</div>\n");
      out.write("								   <div class=\"clearfix\"></div>	\n");
      out.write("								 </a></li>\n");
      out.write("								<li><a href=\"#\">\n");
      out.write("								   <div class=\"user_img\"><img src=\"images/2.jpg\" alt=\"\"></div>\n");
      out.write("								   <div class=\"notification_desc\">\n");
      out.write("									<p>Lorem ipsum dolor amet </p>\n");
      out.write("									<p><span>1 hour ago</span></p>\n");
      out.write("									</div>\n");
      out.write("								   <div class=\"clearfix\"></div>	\n");
      out.write("								</a></li>\n");
      out.write("								 <li>\n");
      out.write("									<div class=\"notification_bottom\">\n");
      out.write("										<a href=\"#\">See all notifications</a>\n");
      out.write("									</div> \n");
      out.write("								</li>\n");
      out.write("							</ul>\n");
      out.write("						</li>	\n");
      out.write("						<li class=\"dropdown head-dpdn\">\n");
      out.write("							<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fa fa-tasks\"></i><span class=\"badge blue1\">8</span></a>\n");
      out.write("							<ul class=\"dropdown-menu\">\n");
      out.write("								<li>\n");
      out.write("									<div class=\"notification_header\">\n");
      out.write("										<h3>You have 8 pending task</h3>\n");
      out.write("									</div>\n");
      out.write("								</li>\n");
      out.write("								<li><a href=\"#\">\n");
      out.write("									<div class=\"task-info\">\n");
      out.write("										<span class=\"task-desc\">Database update</span><span class=\"percentage\">40%</span>\n");
      out.write("										<div class=\"clearfix\"></div>	\n");
      out.write("									</div>\n");
      out.write("									<div class=\"progress progress-striped active\">\n");
      out.write("										<div class=\"bar yellow\" style=\"width:40%;\"></div>\n");
      out.write("									</div>\n");
      out.write("								</a></li>\n");
      out.write("								<li><a href=\"#\">\n");
      out.write("									<div class=\"task-info\">\n");
      out.write("										<span class=\"task-desc\">Dashboard done</span><span class=\"percentage\">90%</span>\n");
      out.write("									   <div class=\"clearfix\"></div>	\n");
      out.write("									</div>\n");
      out.write("									<div class=\"progress progress-striped active\">\n");
      out.write("										 <div class=\"bar green\" style=\"width:90%;\"></div>\n");
      out.write("									</div>\n");
      out.write("								</a></li>\n");
      out.write("								<li><a href=\"#\">\n");
      out.write("									<div class=\"task-info\">\n");
      out.write("										<span class=\"task-desc\">Mobile App</span><span class=\"percentage\">33%</span>\n");
      out.write("										<div class=\"clearfix\"></div>	\n");
      out.write("									</div>\n");
      out.write("								   <div class=\"progress progress-striped active\">\n");
      out.write("										 <div class=\"bar red\" style=\"width: 33%;\"></div>\n");
      out.write("									</div>\n");
      out.write("								</a></li>\n");
      out.write("								<li><a href=\"#\">\n");
      out.write("									<div class=\"task-info\">\n");
      out.write("										<span class=\"task-desc\">Issues fixed</span><span class=\"percentage\">80%</span>\n");
      out.write("									   <div class=\"clearfix\"></div>	\n");
      out.write("									</div>\n");
      out.write("									<div class=\"progress progress-striped active\">\n");
      out.write("										 <div class=\"bar  blue\" style=\"width: 80%;\"></div>\n");
      out.write("									</div>\n");
      out.write("								</a></li>\n");
      out.write("								<li>\n");
      out.write("									<div class=\"notification_bottom\">\n");
      out.write("										<a href=\"#\">See all pending tasks</a>\n");
      out.write("									</div> \n");
      out.write("								</li>\n");
      out.write("							</ul>\n");
      out.write("						</li>	\n");
      out.write("					</ul>\n");
      out.write("					<div class=\"clearfix\"> </div>\n");
      out.write("				</div>\n");
      out.write("				<!--notification menu end -->\n");
      out.write("				<div class=\"clearfix\"> </div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"header-right\">\n");
      out.write("				\n");
      out.write("				\n");
      out.write("				<!--search-box-->\n");
      out.write("				<div class=\"search-box\">\n");
      out.write("					<form class=\"input\">\n");
      out.write("						<input class=\"sb-search-input input__field--madoka\" placeholder=\"Search...\" type=\"search\" id=\"input-31\" />\n");
      out.write("						<label class=\"input__label\" for=\"input-31\">\n");
      out.write("							<svg class=\"graphic\" width=\"100%\" height=\"100%\" viewBox=\"0 0 404 77\" preserveAspectRatio=\"none\">\n");
      out.write("								<path d=\"m0,0l404,0l0,77l-404,0l0,-77z\"/>\n");
      out.write("							</svg>\n");
      out.write("						</label>\n");
      out.write("					</form>\n");
      out.write("				</div><!--//end-search-box-->\n");
      out.write("				\n");
      out.write("				<div class=\"profile_details\">		\n");
      out.write("					<ul>\n");
      out.write("						<li class=\"dropdown profile_details_drop\">\n");
      out.write("							<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("								<div class=\"profile_img\">	\n");
      out.write("									<span class=\"prfil-img\"><img src=\"images/2.jpg\" alt=\"\"> </span> \n");
      out.write("									<div class=\"user-name\">\n");
      out.write("									<p>");
      out.print(a.getName() );
      out.write("</p>\n");
      out.write("									<span>");
      out.print(a.getEmail() );
      out.write("</span>\n");
      out.write("									</div>\n");
      out.write("									<i class=\"fa fa-angle-down lnr\"></i>\n");
      out.write("									<i class=\"fa fa-angle-up lnr\"></i>\n");
      out.write("									<div class=\"clearfix\"></div>	\n");
      out.write("								</div>	\n");
      out.write("							</a>\n");
      out.write("							<ul class=\"dropdown-menu drp-mnu\">\n");
      out.write("								<li> <a href=\"#\"><i class=\"fa fa-cog\"></i> Settings</a> </li> \n");
      out.write("								<li> <a href=\"#\"><i class=\"fa fa-user\"></i> My Account</a> </li> \n");
      out.write("								<li> <a href=\"#\"><i class=\"fa fa-suitcase\"></i> Profile</a> </li> \n");
      out.write("								<li> <a href=\"#\"><i class=\"fa fa-sign-out\"></i> Logout</a> </li>\n");
      out.write("							</ul>\n");
      out.write("						</li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"clearfix\"> </div>				\n");
      out.write("			</div>\n");
      out.write("			<div class=\"clearfix\"> </div>	\n");
      out.write("		</div>\n");
      out.write("		<!-- //header-ends -->\n");
      out.write("	</div>");
      out.write("\n");
      out.write("<div class=\"row\" style=\"margin-left:400px;margin-top:100px;width:800px;\">\n");
      out.write("	<div class=\"col-md-6 validation-grids widget-shadow\" data-example-id=\"basic-forms\"> \n");
      out.write("		<div class=\"form-title\">\n");
      out.write("			<h4>Book Hall</h4>\n");
      out.write("		</div>\n");
      out.write("					 \n");
      out.write("		<div class=\"form-body\">\n");
      out.write("			<form data-toggle=\"validator\" action=\"AdminController\" method=\"post\">\n");
      out.write("			\n");
      out.write("			");
String msg = (String)request.getAttribute("msg"); 
      out.write("\n");
      out.write("            ");

            	if(msg != null)
            	{
            
      out.write("\n");
      out.write("            <h3>");
      out.print(msg );
      out.write("</h3>\n");
      out.write("            ");

            	}
            
      out.write("\n");
      out.write("            <br>\n");
      out.write("			\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<input type=\"email\" class=\"form-control\" id=\"inputName\" name=\"email\" placeholder=\"Member Email\" required>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<input type=\"text\" class=\"form-control\" id=\"inputName\" name=\"b_subject\" placeholder=\"Enter Event Name\" required>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<input type=\"date\" class=\"form-control\" id=\"inputName\" name=\"b_date\" placeholder=\"Enter Date\" required>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<button type=\"submit\" class=\"btn btn-primary enabled\" name=\"action\" value=\"adminBookHall\">Book Now</button>\n");
      out.write("				</div>\n");
      out.write("			</form>\n");
      out.write("		</div>\n");
      out.write("	</div>	\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
