/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-13 09:56:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Admin;
import dao.AdminDao;
import java.util.List;

public final class admin_002dheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Admin");
    _jspx_imports_classes.add("dao.AdminDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("  <!-- Required meta tags -->\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("  <title>E-Society Admin Header</title>\n");
      out.write("\n");
      out.write("  <!-- Template CSS -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"admin/assets/css/style-starter.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("	\n");
      out.write("  <!-- google fonts -->\n");
      out.write("  <link href=\"//fonts.googleapis.com/css?family=Nunito:300,400,600,700,800,900&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head></head>\n");
      out.write("<body class=\"sidebar-menu-collapsed\">\n");
      out.write("<section>\n");
      out.write("  <!-- sidebar menu start -->\n");
      out.write("  <div class=\"sidebar-menu sticky-sidebar-menu\">\n");
      out.write("\n");
      out.write("    <!-- logo start -->\n");
      out.write("    <div class=\"logo\">\n");
      out.write("      <h1><a href=\"admin-home.jsp\">E-Society</a></h1>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  <!-- if logo is image enable this -->\n");
      out.write("    <!-- image logo --\n");
      out.write("    <div class=\"logo\">\n");
      out.write("      <a href=\"admin-home.jsp\">\n");
      out.write("        <img src=\"image-path\" alt=\"Your logo\" title=\"Your logo\" class=\"img-fluid\" style=\"height:35px;\" />\n");
      out.write("      </a>\n");
      out.write("    </div>\n");
      out.write("    <!-- //image logo -->\n");
      out.write("\n");
      out.write("    <div class=\"logo-icon text-center\">\n");
      out.write("      <a href=\"admin-home.jsp\" title=\"logo\"><img src=\"admin/assets/images/logo.png\" alt=\"logo-icon\"> </a>\n");
      out.write("    </div>\n");
      out.write("    <!-- //logo end -->\n");
      out.write("\n");
      out.write("    <div class=\"sidebar-menu-inner\">\n");
      out.write("\n");
      out.write("      <!-- sidebar nav start -->\n");
      out.write("      <ul class=\"nav nav-pills nav-stacked custom-nav\">\n");
      out.write("        <li class=\"active\"><a href=\"admin-home.jsp\"><i class=\"fa fa-tachometer\"></i><span> Dashboard</span></a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"menu-list\">\n");
      out.write("          <a href=\"#\"><i class=\"fa fa-cogs\"></i>\n");
      out.write("            <span>Elements <i class=\"lnr lnr-chevron-right\"></i></span></a>\n");
      out.write("          <ul class=\"sub-menu-list\">\n");
      out.write("            <li><a href=\"carousels.html\">Carousels</a> </li>\n");
      out.write("            <li><a href=\"cards.html\">Default cards</a> </li>\n");
      out.write("            <li><a href=\"people.html\">People cards</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li><a href=\"pricing.html\"><i class=\"fa fa-table\"></i> <span>Pricing tables</span></a></li>\n");
      out.write("        <li><a href=\"blocks.html\"><i class=\"fa fa-th\"></i> <span>Content blocks</span></a></li>\n");
      out.write("        <li><a href=\"forms.html\"><i class=\"fa fa-file-text\"></i> <span>Forms</span></a></li>\n");
      out.write("      </ul>\n");
      out.write("      <!-- //sidebar nav end -->\n");
      out.write("      <!-- toggle button start -->\n");
      out.write("      <a class=\"toggle-btn\">\n");
      out.write("        <i class=\"fa fa-angle-double-left menu-collapsed__left\"><span>Collapse Sidebar</span></i>\n");
      out.write("        <i class=\"fa fa-angle-double-right menu-collapsed__right\"></i>\n");
      out.write("      </a>\n");
      out.write("      <!-- //toggle button end -->\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <!-- //sidebar menu end -->\n");
      out.write("  <!-- header-starts -->\n");
      out.write("  <div class=\"header sticky-header\">\n");
      out.write("\n");
      out.write("    <!-- notification menu start -->\n");
      out.write("    <div class=\"menu-right\">\n");
      out.write("      <div class=\"navbar user-panel-top\">\n");
      out.write("        <div class=\"search-box\">\n");
      out.write("          <form action=\"#search-results.html\" method=\"get\">\n");
      out.write("            <input class=\"search-input\" placeholder=\"Search Here...\" type=\"search\" id=\"search\">\n");
      out.write("            <button class=\"search-submit\" value=\"\"><span class=\"fa fa-search\"></span></button>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"user-dropdown-details d-flex\">\n");
      out.write("          <div class=\"profile_details_left\">\n");
      out.write("            <ul class=\"nofitications-dropdown\">\n");
      out.write("              <li class=\"dropdown\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"true\"><i\n");
      out.write("                    class=\"fa fa-bell-o\"></i><span class=\"badge blue\">3</span></a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li>\n");
      out.write("                    <div class=\"notification_header\">\n");
      out.write("                      <h3>You have 3 new notifications</h3>\n");
      out.write("                    </div>\n");
      out.write("                  </li>\n");
      out.write("                  <li><a href=\"#\" class=\"grid\">\n");
      out.write("                      <div class=\"user_img\"><img src=\"admin/assets/images/avatar1.jpg\" alt=\"\"></div>\n");
      out.write("                      <div class=\"notification_desc\">\n");
      out.write("                        <p>Johnson purchased template</p>\n");
      out.write("                        <span>Just Now</span>\n");
      out.write("                      </div>\n");
      out.write("                    </a></li>\n");
      out.write("                  <li class=\"odd\"><a href=\"#\" class=\"grid\">\n");
      out.write("                      <div class=\"user_img\"><img src=\"admin/assets/images/avatar2.jpg\" alt=\"\"></div>\n");
      out.write("                      <div class=\"notification_desc\">\n");
      out.write("                        <p>New customer registered </p>\n");
      out.write("                        <span>1 hour ago</span>\n");
      out.write("                      </div>\n");
      out.write("                    </a></li>\n");
      out.write("                  <li><a href=\"#\" class=\"grid\">\n");
      out.write("                      <div class=\"user_img\"><img src=\"admin/assets/images/avatar3.jpg\" alt=\"\"></div>\n");
      out.write("                      <div class=\"notification_desc\">\n");
      out.write("                        <p>Lorem ipsum dolor sit amet </p>\n");
      out.write("                        <span>2 hours ago</span>\n");
      out.write("                      </div>\n");
      out.write("                    </a></li>\n");
      out.write("                  <li>\n");
      out.write("                    <div class=\"notification_bottom\">\n");
      out.write("                      <a href=\"#all\" class=\"bg-primary\">See all notifications</a>\n");
      out.write("                    </div>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\"><i\n");
      out.write("                    class=\"fa fa-comment-o\"></i><span class=\"badge blue\">4</span></a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li>\n");
      out.write("                    <div class=\"notification_header\">\n");
      out.write("                      <h3>You have 4 new messages</h3>\n");
      out.write("                    </div>\n");
      out.write("                  </li>\n");
      out.write("                  <li><a href=\"#\" class=\"grid\">\n");
      out.write("                      <div class=\"user_img\"><img src=\"admin/assets/images/avatar1.jpg\" alt=\"\"></div>\n");
      out.write("                      <div class=\"notification_desc\">\n");
      out.write("                        <p>Johnson purchased template</p>\n");
      out.write("                        <span>Just Now</span>\n");
      out.write("                      </div>\n");
      out.write("                    </a></li>\n");
      out.write("                  <li class=\"odd\"><a href=\"#\" class=\"grid\">\n");
      out.write("                      <div class=\"user_img\"><img src=\"admin/assets/images/avatar2.jpg\" alt=\"\"></div>\n");
      out.write("                      <div class=\"notification_desc\">\n");
      out.write("                        <p>New customer registered </p>\n");
      out.write("                        <span>1 hour ago</span>\n");
      out.write("                      </div>\n");
      out.write("                    </a></li>\n");
      out.write("                  <li><a href=\"#\" class=\"grid\">\n");
      out.write("                      <div class=\"user_img\"><img src=\"admin/assets/images/avatar3.jpg\" alt=\"\"></div>\n");
      out.write("                      <div class=\"notification_desc\">\n");
      out.write("                        <p>Lorem ipsum dolor sit amet </p>\n");
      out.write("                        <span>2 hours ago</span>\n");
      out.write("                      </div>\n");
      out.write("                    </a></li>\n");
      out.write("                  <li><a href=\"#\" class=\"grid\">\n");
      out.write("                      <div class=\"user_img\"><img src=\"admin/assets/images/avatar1.jpg\" alt=\"\"></div>\n");
      out.write("                      <div class=\"notification_desc\">\n");
      out.write("                        <p>Johnson purchased template</p>\n");
      out.write("                        <span>Just Now</span>\n");
      out.write("                      </div>\n");
      out.write("                    </a></li>\n");
      out.write("                  <li>\n");
      out.write("                    <div class=\"notification_bottom\">\n");
      out.write("                      <a href=\"#all\" class=\"bg-primary\">See all messages</a>\n");
      out.write("                    </div>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"profile_details\">\n");
      out.write("            <ul>\n");
      out.write("              <li class=\"dropdown profile_details_drop\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" id=\"dropdownMenu3\" aria-haspopup=\"true\"\n");
      out.write("                  aria-expanded=\"true\">\n");
      out.write("                  <div class=\"profile_img\">\n");
      out.write("                    <img src=\"admin/assets/images/profileimg.jpg\" class=\"rounded-circle\" alt=\"\" />\n");
      out.write("                    <div class=\"user-active\">\n");
      out.write("                      <span></span>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </a>\n");
      out.write("                <ul class=\"dropdown-menu drp-mnu\" aria-labelledby=\"dropdownMenu3\">\n");
      out.write("                  <li class=\"user-info\">\n");
      out.write("                    <h5 class=\"user-name\"></h5>\n");
      out.write("                    <span class=\"status ml-2\">Available</span>\n");
      out.write("                  </li>\n");
      out.write("                  <li> <a href=\"admin-profile.jsp\"><i class=\"lnr lnr-user\"></i>My Profile</a> </li>\n");
      out.write("                  <li> <a href=\"#\"><i class=\"lnr lnr-users\"></i>1k Followers</a> </li>\n");
      out.write("                  <li> <a href=\"#\"><i class=\"lnr lnr-cog\"></i>Setting</a> </li>\n");
      out.write("                  <li> <a href=\"#\"><i class=\"lnr lnr-heart\"></i>100 Likes</a> </li>\n");
      out.write("                  <li class=\"logout\"> <a href=\"#sign-up.html\"><i class=\"fa fa-power-off\"></i> Logout</a> </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <!--notification menu end -->\n");
      out.write("  </div>\n");
      out.write("  <!-- //header-ends -->\n");
      out.write(" </section>\n");
      out.write("  \n");
      out.write(" \n");
      out.write("</button>\n");
      out.write("<script>\n");
      out.write("  // When the user scrolls down 20px from the top of the document, show the button\n");
      out.write("  window.onscroll = function () {\n");
      out.write("    scrollFunction()\n");
      out.write("  };\n");
      out.write("\n");
      out.write("  function scrollFunction() {\n");
      out.write("    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {\n");
      out.write("      document.getElementById(\"movetop\").style.display = \"block\";\n");
      out.write("    } else {\n");
      out.write("      document.getElementById(\"movetop\").style.display = \"none\";\n");
      out.write("    }\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  // When the user clicks on the button, scroll to the top of the document\n");
      out.write("  function topFunction() {\n");
      out.write("    document.body.scrollTop = 0;\n");
      out.write("    document.documentElement.scrollTop = 0;\n");
      out.write("  }\n");
      out.write("</script>\n");
      out.write("<!-- /move top -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"admin/assets/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("<script src=\"admin/assets/js/jquery-1.10.2.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- chart js -->\n");
      out.write("<script src=\"admin/assets/js/Chart.min.js\"></script>\n");
      out.write("<script src=\"admin/assets/js/utils.js\"></script>\n");
      out.write("<!-- //chart js -->\n");
      out.write("\n");
      out.write("<!-- Different scripts of charts.  Ex.Barchart, Linechart -->\n");
      out.write("<script src=\"admin/assets/js/bar.js\"></script>\n");
      out.write("<script src=\"admin/assets/js/linechart.js\"></script>\n");
      out.write("<!-- //Different scripts of charts.  Ex.Barchart, Linechart -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"admin/assets/js/jquery.nicescroll.js\"></script>\n");
      out.write("<script src=\"admin/assets/js/scripts.js\"></script>\n");
      out.write("\n");
      out.write("<!-- close script -->\n");
      out.write("<script>\n");
      out.write("  var closebtns = document.getElementsByClassName(\"close-grid\");\n");
      out.write("  var i;\n");
      out.write("\n");
      out.write("  for (i = 0; i < closebtns.length; i++) {\n");
      out.write("    closebtns[i].addEventListener(\"click\", function () {\n");
      out.write("      this.parentElement.style.display = 'none';\n");
      out.write("    });\n");
      out.write("  }\n");
      out.write("</script>\n");
      out.write("<!-- //close script -->\n");
      out.write("\n");
      out.write("<!-- disable body scroll when navbar is in active -->\n");
      out.write("<script>\n");
      out.write("  $(function () {\n");
      out.write("    $('.sidebar-menu-collapsed').click(function () {\n");
      out.write("      $('body').toggleClass('noscroll');\n");
      out.write("    })\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("<!-- disable body scroll when navbar is in active -->\n");
      out.write("\n");
      out.write(" <!-- loading-gif Js -->\n");
      out.write(" <script src=\"admin/assets/js/modernizr.js\"></script>\n");
      out.write(" <script>\n");
      out.write("     $(window).load(function () {\n");
      out.write("         // Animate loader off screen\n");
      out.write("         $(\".se-pre-con\").fadeOut(\"slow\");;\n");
      out.write("     });\n");
      out.write(" </script>\n");
      out.write(" <!--// loading-gif Js -->\n");
      out.write("\n");
      out.write("<!-- Bootstrap Core JavaScript -->\n");
      out.write("<script src=\"admin/assets/js/bootstrap.min.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
