/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-15 13:57:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>E-Society-User Header</title>\n");
      out.write(" <!-- Required meta tags -->\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("  <!-- google fonts -->\n");
      out.write("  <link href=\"//fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("  <!-- google fonts -->\n");
      out.write("  <!-- Template CSS -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"assets/css/style-starter.css\">\n");
      out.write("  <!-- Template CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style-liberty.css\">\n");
      out.write("  \n");
      out.write("  <link rel=\"stylesheet\" href=\"assets/css/dropdown.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("		<!--header-->\n");
      out.write("		  <header id=\"site-header\" class=\"fixed-top\">\n");
      out.write("		    <div class=\"container\">\n");
      out.write("		      <nav class=\"navbar navbar-expand-lg stroke\">\n");
      out.write("		        <h1><a class=\"navbar-brand mr-lg-5\" href=\"index.jsp\">\n");
      out.write("		          <span class=\"log\">E-</span>Society\n");
      out.write("		          </a></h1>\n");
      out.write("		        <!-- if logo is image enable this   \n");
      out.write("		      <a class=\"navbar-brand\" href=\"#index.html\">\n");
      out.write("		          <img src=\"image-path\" alt=\"Your logo\" title=\"Your logo\" style=\"height:35px;\" />\n");
      out.write("		      </a> -->\n");
      out.write("		        <button class=\"navbar-toggler  collapsed bg-gradient\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("		          data-target=\"#navbarTogglerDemo02\" aria-controls=\"navbarTogglerDemo02\" aria-expanded=\"false\"\n");
      out.write("		          aria-label=\"Toggle navigation\">\n");
      out.write("		          <span class=\"navbar-toggler-icon fa icon-expand fa-bars\"></span>\n");
      out.write("		          <span class=\"navbar-toggler-icon fa icon-close fa-times\"></span>\n");
      out.write("		          </span>\n");
      out.write("		        </button>\n");
      out.write("\n");
      out.write("		        <div class=\"collapse navbar-collapse\" id=\"navbarTogglerDemo02\">\n");
      out.write("		          <ul class=\"navbar-nav mr-auto\">\n");
      out.write("		            <li class=\"nav-item active\">\n");
      out.write("		              <a class=\"nav-link\" href=\"index.jsp\">Home <span class=\"sr-only\">(current)</span></a>\n");
      out.write("		            </li>\n");
      out.write("		            <li class=\"nav-item\">\n");
      out.write("		              <a class=\"nav-link\" href=\"about.jsp\">About</a>\n");
      out.write("		            </li>\n");
      out.write("		            <li class=\"nav-item\">\n");
      out.write("		              <a class=\"nav-link\" href=\"#\">Services</a>\n");
      out.write("		            </li>           \n");
      out.write("					<li class=\"nav-item dropdown show\">\n");
      out.write("		              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown1\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("		                Sign In<span class=\"fa fa-angle-down\"></span>\n");
      out.write("		              </a>\n");
      out.write("		              <div class=\"dropdown-menu show\" aria-labelledby=\"navbarDropdown1\">\n");
      out.write("		                <a class=\"dropdown-item\" href=\"member-login.jsp\">Member Sign In</a>\n");
      out.write("		                <a class=\"dropdown-item\" href=\"admin-login.jsp\">Admin Sign In</a>\n");
      out.write("		              </div>\n");
      out.write("		            </li>\n");
      out.write("		            <li class=\"nav-item\">\n");
      out.write("		              <a class=\"nav-link\" href=\"contact.jsp\">Contact</a>\n");
      out.write("		            </li>\n");
      out.write("\n");
      out.write("		          </ul>\n");
      out.write("		        </div>\n");
      out.write("		        <div class=\"d-lg-block d-none\">\n");
      out.write("		          <a href=\"member-signup.jsp\" class=\"btn btn-style btn-secondary\">Member Sign Up</a>\n");
      out.write("		        </div>\n");
      out.write("		        <!-- toggle switch for light and dark theme -->\n");
      out.write("		        <div class=\"mobile-position\">\n");
      out.write("		          <nav class=\"navigation\">\n");
      out.write("		            <div class=\"theme-switch-wrapper\">\n");
      out.write("		              <label class=\"theme-switch\" for=\"checkbox\">\n");
      out.write("		                <input type=\"checkbox\" id=\"checkbox\">\n");
      out.write("			                <div class=\"mode-container\">\n");
      out.write("			                  <i class=\"gg-sun\"></i>\n");
      out.write("			                  <i class=\"gg-moon\"></i>\n");
      out.write("			                </div>\n");
      out.write("		              </label>\n");
      out.write("		            </div>\n");
      out.write("		          </nav>\n");
      out.write("		        </div>\n");
      out.write("		        <!-- //toggle switch for light and dark theme -->\n");
      out.write("		      </nav>\n");
      out.write("		    </div>\n");
      out.write("		  </header>\n");
      out.write("		  <!-- //header -->\n");
      out.write("	\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
